source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa
target ‘MVSP’ do
    
pod 'SDWebImage','3.8.2'
pod 'AFNetworking', '~> 3.0.4’
pod 'JSONModel', '~> 1.2.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SVProgressHUD','~> 2.0.3'
pod 'MD5Digest', '~> 1.1.0'
pod 'MJRefresh','~> 3.1.0’
pod 'FMDB','~> 2.6.2'
pod 'Masonry','~> 1.0.1'

#pod 'UMCCommon'
 # U-Share SDK UI模块（分享面板，建议添加）
#pod 'UMCCommonLog'
#pod 'UMCShare/UI'

#pod 'UMCAnalytics'
#pod 'UMCSecurityPlugins'

# 集成微信(完整版14.4M)
#pod 'UMCShare/Social/WeChat'

# 集成QQ/QZone/TIM(完整版7.6M)
#pod 'UMCShare/Social/QQ'

#pod 'MMDrawerController', '~> 0.6.0'
#腾讯下的Bugly 异常收集
#pod 'Bugly'



end
